services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/ssl:ro

    networks:
      - my-composed-network
    depends_on:
      - app

  app:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-composed-network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_PASSWORD_FILE=/run/secrets/db_password
      - DB_NAME=example

    secrets:
      - db_password

  db:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - my-composed-network
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10


networks:
  my-composed-network:
    driver: bridge



secrets:
  db_password:
    file: ./DB_PASSWORD_FILE
